apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  POSTGRES_USER: sendag
  POSTGRES_PASSWORD: finalpass 
  POSTGRES_DB: aicldb
  POSTGRES_MULTIPLE_DATABASES: "keycloak:keycloak_user:keycloak_password"
